---
- name: Disable services
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  failed_when: false
  with_items:
    - k3s
    - k3s-node
    - k3s-init

- name: RUN pkill -9 -f "k3s/data/[^/]+/bin/containerd-shim-runc"
  register: pkill_containerd_shim_runc
  command: pkill -9 -f "k3s/data/[^/]+/bin/containerd-shim-runc"
  changed_when: "pkill_containerd_shim_runc.rc == 0"
  failed_when: false

- name: Umount k3s filesystems
  include_tasks: umount_with_children.yml
  with_items:
    - /run/k3s
    - /var/lib/kubelet
    - /run/netns
    - /var/lib/rancher/k3s
    - /var/lib/kubelet/pods
    - /var/lib/kubelet/plugins
    - /run/netns/cni-
  loop_control:
    loop_var: mounted_fs

#
# it may become or be a common practice to separate /var/lib/rancher and /var/lib/kubelet into their own volumes.  Maybe it would be better to just move /var altogether, but that's not
# terribly convenient for remote or headless machines (e.g. raspberry pi compute modules, embedded in Turing Pi or Desk Pi where you can't get to single user mode.
# Recommendation, in this case, is to mount a new volume, such as /k3s-data or similar and symlink /var/lib/rancher and /var/lib/kubelet into directories 
# other k3s data points like /run/k3s are small/transient/in memory and shouldn't be on a volume
# 
# The approach is to delete the files in the folders first, then remove the folders/files that are not symlinks in the follow up
#
- name: find service files within the directories that can by symlinks, binaries and data for people who have separate volume and symlink for /var/lib/rancher and /var/lib/kubelet
  ansible.builtin.find:
    paths:
      - /var/lib/rancher/
      - /var/lib/kubelet/
    hidden: true
    recurse: false
    file_type: any
  register: to_delete_files

- name: find service files, binaries and data for people who have separate volume and symlink for /var/lib/rancher and /var/lib/kubelet
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  ignore_errors: true
  with_items: "{{ to_delete_files.files }}"

- name: Remove service files, binaries and data
  ansible.builtin.file:
    name: "{{ item }}"
    state: absent
  ignore_errors: true
  with_items:
    - /usr/local/bin/k3s
    - "{{ systemd_dir }}/k3s.service"
    - "{{ systemd_dir }}/k3s-node.service"
    - /run/k3s
    - /run/flannel
    - /etc/rancher/
    - /var/lib/kubelet/
    - /var/lib/rancher/
    - /var/lib/cni/

- name: Reload daemon_reload
  systemd:
    daemon_reload: yes

- name: Remove linux-modules-extra-raspi
  apt: name=linux-modules-extra-raspi state=absent

- name: Remove tmp director used for manifests
  file:
    path: /tmp/k3s
    state: absent

- name: Reboot and wait for node to come back up
  reboot:
    reboot_timeout: 3600

